
-- create schema acw before running this

CREATE TABLE "ADW_USER"."VECTOR" 
   (	"GAMEID" NUMBER, 
	"POSX" NUMBER, 
	"POSY" NUMBER, 
	"DIRX" NUMBER, 
	"DIRY" NUMBER, 
	"TSSTART" NUMBER, 
	"TSEND" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP";

CREATE TABLE "ADW_USER"."EVENT" (	
  	"GAMEID" NUMBER, 
 	"TEAM" VARCHAR(10),
	"EVENTTYPE" VARCHAR(16),
	"VALUE" NUMBER, 	 
	"TS" NUMBER
) DEFAULT COLLATION "USING_NLS_COMP";

