
-- Generated by ORDS REST Data Services 19.3.0.r3191521
-- Schema: ADW_USER  Date: Wed Jan 22 02:00:07 2020 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ADW_USER',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'acw',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'acw',
      p_base_path      => '/game/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'acw',
      p_pattern        => 'vector/:gameid',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'acw',
      p_pattern        => 'vector/:gameid',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from vector where gameid=:gameid');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'acw',
      p_pattern        => 'vector/:gameid',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'BEGIN 

  INSERT INTO vector (gameid, posx, posy, dirx, diry, tsstart, tsend)
    SELECT :gameid, j.*
    FROM   json_table(:body FORMAT JSON, ''$[*]''
           COLUMNS (posx, posy, dirx, diry, tsstart, tsend)) j;

  COMMIT;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'acw',
      p_pattern            => 'vector/:gameid',
      p_method             => 'POST',
      p_name               => 'gameid',
      p_bind_variable_name => 'gameid',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'acw',
      p_pattern        => 'event/:gameid',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'acw',
      p_pattern        => 'event/:gameid',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from event where gameid=:gameid');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'acw',
      p_pattern        => 'event/:gameid',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'BEGIN 

  INSERT INTO event (gameid, team, eventtype, value, ts)
    SELECT :gameid, j.*
    FROM   json_table(:body FORMAT JSON, ''$[*]''
           COLUMNS (team, eventtye, value, ts)) j;

  COMMIT;

END;');

    
        
COMMIT;

END;